# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-28 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encryption',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('public_key', models.CharField(max_length=3220)),
                ('private_key_part', models.CharField(max_length=3220)),
                ('recovery', models.CharField(max_length=3220)),
                ('password', models.CharField(max_length=3220)),
            ],
        ),
    ]
