# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-30 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryption',
            name='private_key_part',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='encryption',
            name='public_key',
            field=models.CharField(max_length=10),
        ),
    ]
